# Generated by Django 5.1.14 on 2025-11-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
        ("tasks", "0059_task_completion_id_updated_at_idx_async"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oss2ExportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "can_delete_objects",
                    models.BooleanField(
                        blank=True,
                        help_text="Deletion from storage enabled",
                        null=True,
                        verbose_name="can_delete_objects",
                    ),
                ),
                (
                    "bucket",
                    models.TextField(
                        blank=True,
                        help_text="OSS bucket name",
                        null=True,
                        verbose_name="bucket",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="OSS bucket prefix",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "oss_access_key_id",
                    models.TextField(
                        blank=True,
                        help_text="OSS Access Key ID",
                        null=True,
                        verbose_name="oss_access_key_id",
                    ),
                ),
                (
                    "oss_access_key_secret",
                    models.TextField(
                        blank=True,
                        help_text="OSS Access Key Secret",
                        null=True,
                        verbose_name="oss_access_key_secret",
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(
                        blank=True,
                        help_text="OSS Endpoint",
                        null=True,
                        verbose_name="endpoint",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Oss2ExportStorageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_exists",
                    models.BooleanField(
                        default=True,
                        help_text="Whether object under external link still exists",
                        verbose_name="object exists",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update time",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="tasks.annotation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Oss2ImportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "bucket",
                    models.TextField(
                        blank=True,
                        help_text="OSS bucket name",
                        null=True,
                        verbose_name="bucket",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="OSS bucket prefix",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "oss_access_key_id",
                    models.TextField(
                        blank=True,
                        help_text="OSS Access Key ID",
                        null=True,
                        verbose_name="oss_access_key_id",
                    ),
                ),
                (
                    "oss_access_key_secret",
                    models.TextField(
                        blank=True,
                        help_text="OSS Access Key Secret",
                        null=True,
                        verbose_name="oss_access_key_secret",
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(
                        blank=True,
                        help_text="OSS Endpoint",
                        null=True,
                        verbose_name="endpoint",
                    ),
                ),
                (
                    "recursive_scan",
                    models.BooleanField(
                        default=False,
                        help_text="Perform recursive scan over the bucket content",
                        verbose_name="recursive scan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Oss2ImportStorageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.TextField(help_text="External link key", verbose_name="key"),
                ),
                (
                    "object_exists",
                    models.BooleanField(
                        default=True,
                        help_text="Whether object under external link still exists",
                        verbose_name="object exists",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "row_group",
                    models.IntegerField(
                        blank=True, help_text="Parquet row group", null=True
                    ),
                ),
                (
                    "row_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Parquet row index, or JSON[L] object index",
                        null=True,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
